[33mcommit badd6c421da13788b44c892973ca859b0c289a36[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mfeature/payment[m[33m, [m[1;31morigin/feature/payment[m[33m)[m
Author: GUILLERMO CIRIA GONZÁLEZ <guicirgon@alum.us.es>
Date:   Sun Nov 16 18:26:54 2025 +0100

    style: :lipstick: Changed language to spanish

[33mcommit 504879cbabce1284ac3e44cb020e82274b3254bb[m
Author: GUILLERMO CIRIA GONZÁLEZ <guicirgon@alum.us.es>
Date:   Sun Nov 16 18:22:16 2025 +0100

    feat: :sparkles: Finished Payments
    
    Finished all realted payments; only left to do "contrarrembolso", also enhanced and upgraded some order views

[33mcommit f34988d18901475417e77860261dc0db6b969dc7[m
Author: GUILLERMO CIRIA GONZÁLEZ <guicirgon@alum.us.es>
Date:   Sun Nov 16 09:38:28 2025 +0100

    Created feature

[33mcommit fffbc07cb5ec08231f03b59217f45c1d493fe07f[m
Merge: 564c723 28ac066
Author: GUILLERMO CIRIA GONZÁLEZ <guicirgon@alum.us.es>
Date:   Sun Nov 16 09:19:47 2025 +0100

    Merge remote-tracking branch 'origin/feature/order' into feature/payment

[33mcommit 28ac06648c121c2ce207e69d629a7bf833e6c4d6[m
Author: Ultimate88 <alejandrogonzalez88x@gmail.com>
Date:   Sat Nov 15 22:02:19 2025 +0100

    feat: :sparkles: Add order functionalities and provisional views

[33mcommit 5d63bed221382fa4a8f1f08e75c980c867941927[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Fri Nov 14 21:19:03 2025 +0100

    feat: :card_file_box: Users seeder added to seed_all.py file

[33mcommit f5ca33f7d55e12ed6bcf9c4b1507a115de41998b[m
Merge: 19956b4 b748be9
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Fri Nov 14 21:11:02 2025 +0100

    Merge branch 'feature/customer' into develop

[33mcommit b748be97a0a3125b1cfe041eddfb25b538f3131d[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Fri Nov 14 21:10:44 2025 +0100

    feat: :card_file_box: Added a customer seeder

[33mcommit 19956b4f12e7c4c5813afcf0235bad86a52f2295[m
Merge: 44a940d 04411c4
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Fri Nov 14 20:44:40 2025 +0100

    Merge branch 'feature/customer' into develop

[33mcommit 04411c451268d8c020cf5ce54d765fa01013b130[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Fri Nov 14 20:41:27 2025 +0100

    style: :lipstick: Changed customer views and modified customer model

[33mcommit 564c72350bf74c3cecabd31a14555fb59d9bd40f[m[33m ([m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m, [m[1;32mmain[m[33m)[m
Author: Manuel Jesús Niza Cobo <mannizcob@alum.us.es>
Date:   Thu Nov 13 14:55:25 2025 +0100

    Update README.md

[33mcommit 44a940d8678ae2400c7e69f016e66f823ffb1a3c[m[33m ([m[1;31morigin/feature/catalog[m[33m)[m
Author: Manuel.J Niza Cobo <manolo3399@gmail.com>
Date:   Thu Nov 13 14:51:00 2025 +0100

    fix: Se incorpora el gitignore

[33mcommit 2faf8f40f6ae6c65567d49a860c7bb059232fa50[m
Author: Manuel.J Niza Cobo <manolo3399@gmail.com>
Date:   Thu Nov 13 14:49:21 2025 +0100

    feat: Se implementa el catalogo con los productos de ejemplo

[33mcommit 9b9cb9ea1a55f42fe2cc243605ab5068ea7e558a[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Thu Nov 13 12:56:37 2025 +0100

    feat: :sparkles: Editing profiles functionality fully implemented

[33mcommit 9224504739115877dc3ae30257d6d5d87d0f9f51[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Thu Nov 13 12:30:45 2025 +0100

    feat: :lipstick: Added profile view, message errors at register view and a phone validator at the register form

[33mcommit d9c776a5ed6748d4e9055e2927307d7a64b76278[m
Merge: 40136dc b378022
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Tue Nov 11 23:44:08 2025 +0100

    Merge branch 'main' of https://github.eii.us.es/QPJ7754/PGPI-G1.7

[33mcommit 40136dce7ddd6e55b24c9bf1d7068018e08cb56a[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Tue Nov 11 23:43:59 2025 +0100

    feat: :sparkles: Added customer functionalities and base views

[33mcommit b37802290b9fcee8830d979ff7502ce4300217f4[m
Author: ADRIÁN MIGUEL CHABRERA RUBIO <adrcharub@alum.us.es>
Date:   Tue Nov 11 13:22:58 2025 +0100

    Update README.md

[33mcommit 6031a4155a4afbb32ef5c3ba47609a33a57b9cb2[m
Author: ADRIÁN MIGUEL CHABRERA RUBIO <adrcharub@alum.us.es>
Date:   Tue Nov 11 13:04:43 2025 +0100

    Update README.md

[33mcommit 014cc886e19f5bc3ba2c3447c8a2344a7ca88d6f[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Tue Nov 11 11:53:40 2025 +0100

    build: :see_no_evil: Modified gitignore file

[33mcommit c89f841aafdfc758c524561267cefa83452f2686[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Tue Nov 11 11:52:58 2025 +0100

    build: :see_no_evil: Modified .gitignore file and deleted autogenerated files

[33mcommit a0761918541d0e633bfd1dd56fbbb7fcb4153248[m
Author: AdrianChabrera <adrianchabrera@gmail.com>
Date:   Tue Nov 11 11:47:52 2025 +0100

    build: :see_no_evil: Added .gitignore file

[33mcommit 0540a84b8f591354ba87dc5158ed808c58e5d070[m
Author: Manuel Jesús Niza Cobo <mannizcob@alum.us.es>
Date:   Mon Nov 10 00:14:11 2025 +0100

    Add files via upload

[33mcommit 4ce38916263c97bab74e30a3082cdc2dfeec3121[m
Author: GUILLERMO CIRIA GONZÁLEZ <guicirgon@alum.us.es>
Date:   Mon Nov 10 00:08:37 2025 +0100

    Update README.md

[33mcommit 384a1baf38048c45db1dba216c4f252f3bbdabbc[m
Author: ALEJANDRO GONZALEZ MACIAS <alegonmac@alum.us.es>
Date:   Sun Nov 9 23:58:48 2025 +0100

    Add files via upload

[33mcommit bfcef0c4ff4a562ab864198636c11b4e866d303d[m
Author: ALEJANDRO GONZALEZ MACIAS <alegonmac@alum.us.es>
Date:   Sun Nov 9 23:56:25 2025 +0100

    Add files via upload

[33mcommit 00d0d09ea5909e83d114b13a0fe2683269cf3b66[m
Author: ALEJANDRO GONZALEZ MACIAS <alegonmac@alum.us.es>
Date:   Sun Nov 9 23:53:24 2025 +0100

    Add files via upload

[33mcommit ddab60069bb152b2b99fe95d1aa165c6352f9f62[m
Author: ALEJANDRO GONZALEZ MACIAS <alegonmac@alum.us.es>
Date:   Sun Nov 9 23:53:13 2025 +0100

    Delete docs/1º iteración/Informe de Seguimiento de Costes Sprint 1.png

[33mcommit 825ec68f8f76dd6fd756cf82b58ce90c208f847f[m
Author: JOSE EGIDO CARNERERO <josegicar@alum.us.es>
Date:   Sun Nov 9 23:51:46 2025 +0100

    Add files via upload

[33mcommit 272441685336e535583f5b51fd2a8a74c126d357[m
Author: ALEJANDRO GONZALEZ MACIAS <alegonmac@alum.us.es>
Date:   Sun Nov 9 23:39:16 2025 +0100

    Add files via upload

[33mcommit 3419f4c01c337b82caaabb03f6a17dedf824fe01[m
Author: ADRIÁN MIGUEL CHABRERA RUBIO <adrcharub@alum.us.es>
Date:   Sun Nov 9 23:26:15 2025 +0100

    Add files via upload

[33mcommit a588851e64c386dcfabc6ea3157817c7b631be50[m
Author: ADRIÁN MIGUEL CHABRERA RUBIO <adrcharub@alum.us.es>
Date:   Sun Nov 9 22:37:13 2025 +0100

    Delete docs/1º iteración/dummy.txt

[33mcommit ea7d32c7be2086e12fc9b874e3ed55e1256b308b[m
Author: ADRIÁN MIGUEL CHABRERA RUBIO <adrcharub@alum.us.es>
Date:   Sun Nov 9 22:36:50 2025 +0100

    Add files via upload

[33mcommit 0f05279b84b13fe1fafe2898c22989d68b3d0505[m
Author: ADRIÁN MIGUEL CHABRERA RUBIO <adrcharub@alum.us.es>
Date:   Sun Nov 9 22:34:02 2025 +0100

    Create dummy.txt

[33mcommit ccd1198175a0a1afbcc0235cbc77b09e492f23b6[m
Author: ALEJANDRO GONZALEZ MACIAS <alegonmac@alum.us.es>
Date:   Sat Nov 8 18:13:45 2025 +0100

    Update README.md

[33mcommit ca5f7290652105f011c7907b8d107ba5c9be3e6a[m
Author: Ultimate88 <alejandrogonzalez88x@gmail.com>
Date:   Sat Nov 8 16:59:42 2025 +0100

    Inicializar proyecto Django y MariaDB

[33mcommit 045aa84fd0152155d6a4b914caf1320600e6d8c1[m
Author: GUILLERMO CIRIA GONZÁLEZ <guicirgon@alum.us.es>
Date:   Wed Nov 5 17:08:01 2025 +0100

    Update README.md

[33mcommit ad8f3719174457f7036dd82d6052894fb93105b6[m
Author: Manuel Jesús Niza Cobo <mannizcob@alum.us.es>
Date:   Fri Oct 31 16:50:18 2025 +0100

    Add files via upload

[33mcommit bb1f57e42355908405ed2e70a2150e452956b8ee[m
Author: Manuel Jesús Niza Cobo <mannizcob@alum.us.es>
Date:   Fri Oct 31 16:49:59 2025 +0100

    Delete docs/6ª semana/Archivos cambiados de semanas pasadas + Changelog/ATRIBUTOS DE ACTIVIDAD_v2.pdf

[33mcommit 07050713bb65df293260b25fb5fbea73af